import Head from "next/head"
import Image from "next/image"
import { useState } from "react"

function Login() {

    const [login, setLogin] = useState(false)



    return (
        <div className="relative 
        flex 
        flex-col
        w-screen
        h-[100vh]
        md:items-center 
        md:justify-center
        md:bg-transparent
        md:bg-black">
            <Head>
                <title>Netflix</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Image
                src="https://yourspanishguide.com/wp-content/uploads/2021/02/dUyCkp.jpg"
                alt=""
                className="-z-10 !hidden opacity-60 sm:!inline cover"
                fill
            />
            

                <img src="https://rb.gy/ulxxee"
                    width={150}
                    height={100}
                    className="absolute left-4 top-4 cursor-pointer object-contain" />


                <form className="relative 
                mt-24 
                space-y-8 
                rounded 
                bg-black/75 
                py-10 px-6 
                md:mt-0 
                md:max-w-md md:px-14">
                    <h1 className="text-4xl font-semibold">Sign In</h1>
                    <div className="space-y-4">
                        <label className="inline-block w-full">
                            <input type="email" placeholder="Email" className="input" />
                        </label>
                        <label className="inline-block w-full">
                            <input type="password" placeholder="Password" className="input" />
                        </label>
                    </div>
                    <button className="w-full rounded bg-[#e50914] py-3 font-semibold">Sign In</button>

                    <div className="text-[gray]">
                        New to netflix? {' '}
                        <button type="submit" className="text-white hover:underline">Sign up now</button>
                    </div>
                </form>
            

        </div>
    )
}

export default Login